---
title: "Título"
author: "Igo da Costa Andrade"

# Metadados
booktitle: "Mecânica Clássica"
#booksubtitle: "Subtítulo do Livro"
bookauthors: "Taylor, J. R."
bookaddres: "Porto Alegre"
bookpublisher: "Bookman"
bookyear: "2013"
chaptertitle: "Leis de Newton do Movimento"
chapternumber: "1"
maincolor: "dc2531"

output: 
  bookdown::pdf_document2:
    template: template.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
use_python("~/anaconda3/envs/science/bin/python")
```

\section*{PROBLEMAS}

\subsection*{Seção 1.2 Espaço e Tempo}

\begin{enumerate}
  \item Dados dois vetores $\vet{v} = \ux + \uy$ e $\vet{c} = \ux + \uz$, determine $\vet{b} + \vet{c}$, $5\vet{b} + 2\vet{c}$, $\vet{b} \cdot \vet{c}$ e $\vet{b} \times \vet{c}$.\\
  \iniSol
    \begin{small}
    \begin{align*}
      \vet{b} + \vet{c} &= (\ux + \uy) + (\ux + \uz) = \ux + \uy  + \ux + \uz = 2\ux + \uy + \uz\\
      5\vet{b} + 2\vet{c} &= 5 (\ux + \uy) + 2(\ux + \uz) = 5\ux + 5\uy + 2\ux + 2\uz = 7\ux + 5\uy + 2\uz\\
      \vet{b} \cdot \vet{c} &= (\ux + \uy) \cdot (\ux + \uz) = \ux \cdot \ux + \ux \cdot \uz + \uy \cdot \ux + \uy \cdot \uz = 1 + 0 + 0 + 0 = 1\\
      \vet{b} \times \vet{c} &= 
      \begin{vmatrix}
        \ux & \uy & \uz\\
        1 & 1 & 0\\
        1 & 0 & 1
      \end{vmatrix} = 
      \ux \begin{vmatrix}
        1 & 0\\
        0 & 1
      \end{vmatrix} -
      \uy \begin{vmatrix}
        1 & 0\\
        1 & 1
      \end{vmatrix} + 
      \uz \begin{vmatrix}
        1 & 1\\
        1 & 0
      \end{vmatrix}
      \\
      &= \ux (1 \cdot 1 - 0 \cdot 0) - \uy (1 \cdot 1 - 1 \cdot 0) + \uz (1 \cdot 0 - 1 \cdot 1) = \ux - \uy - \uz
    \end{align*}
    \end{small}
  \fimSol
  %%%%
  \item Dois vetores são dados como $\vet{b} = (1,2,3)$ e $\vet{c} = (3, 2, 1)$. (Lembre-se de que essas declarações são uma forma compacta de fornacer as componentes dos vetores.) Determine $\vet{b} + \vet{c}$, $5\vet{b} + 2\vet{c}$, $\vet{b} \cdot \vet{c}$ e $\vet{b} \times \vet{c}$.\\
  \iniSol
    \begin{small}
    \begin{align*}
      \vet{b} + \vet{c} &= (1+3, 2+2, 3+1) = (4, 4, 4) = 2\ux + 4\uy + 4\uz\\
      5\vet{b} + 2\vet{c} &= (5\cdot 1+ 2 \cdot 3, 5\cdot 2+ 2 \cdot 2, 5\cdot 3+ 2 \cdot 1) = (5+6, 10+4, 15+2) = (11, 14,17) = 11\ux + 14\uy + 17\uz\\
      \vet{b} \cdot \vet{c} &= 1 \cdot 3 + 2 \cdot 2 + 3 \cdot 1 = 3 + 4 + 3 = 10\\
      \vet{b} \times \vet{c} &= 
      \begin{vmatrix}
        \ux & \uy & \uz\\
        1 & 2 & 3\\
        3 & 2 & 1
      \end{vmatrix}
      = \ux \begin{vmatrix}
      2 & 3\\
      2 & 1
      \end{vmatrix}
      - \uy \begin{vmatrix}
        1 & 3\\
        3 & 1
      \end{vmatrix}
      + \uz \begin{vmatrix}
        1 & 2\\
        3 & 2
      \end{vmatrix}
      \\ &= \ux (2 \cdot 1 - 2 \cdot 3) - \uy (1 \cdot 1 - 3 \cdot 3) + \uz (1 \cdot 2 - 3 \cdot 2) = -4\ux + 8\uy -4\uz
    \end{align*}
    \end{small}
  \fimSol
  %%%%
  \item Aplicando o teorema de Pitágorás (a versão comum bidimensional) duas vezes, mostre que o comprimento $r$ de um vetor tridimensional $\vet{r} = (x, y,z)$ satisaz $r^2 = x^2 + y^2 + z^2$.\\
  \iniSol
    \begin{figure}[H]
      \centering
      \tdplotsetmaincoords{75}{125}
      \begin{tikzpicture}[tdplot_main_coords]
        \draw[-latex] (0,0,0) -- (5, 0, 0) node[above] {$x$}; 
        \draw[-latex] (0,0,0) -- (0, 5, 0) node[above] {$y$};
        \draw[-latex] (0,0,0) -- (0, 0, 5) node[above] {$z$};
        \draw[-latex, thick] (0,0,0) -- (2, 4, 3) node [above] {$\vet{r}$} node[right] {$P$};
        \draw[dashed] (2, 0, 0) node[above] {$x$} node[below] {$A$}-- (2, 4, 0) node[below] {$P^\prime$} -- (0, 4, 0) node[below] {$B$} node[above] {$y$};
        \draw[dashed] (0, 0, 0) node[left, xshift=-5pt] {$O$} -- (2, 4, 0) -- (2, 4, 3) -- (0, 0, 3) node[left] {$z$};
        \draw (2, 0, 0) -- ++(-0.4, 0, 0) -- ++(0, 0.4, 0) -- ++(0.4, 0, 0);
        \filldraw (2, 0, 0) ++ (-0.2, 0.2, 0) circle (0.8pt);
        \draw (2, 4, 0.4) -- ++ (-0.2, -0.4, 0) -- ++(0, 0, -0.4);
        \filldraw (2, 4, 0)  ++ (-0.1, -0.2, 0.2) circle (0.5pt);
      \end{tikzpicture}
    \end{figure}
    Conforme figura acima, consideremos o vetor $\vet{r} = (x, y, z)$ localizado no ponto $P$, tal que sua projeção ortogonal no plano $xy$ é ponto $P^\prime = (x,y, 0)$. 
    %%
    No plano $xy$, tomamos o triângulo $OAP^\prime$, retângulo no ponto $A = (x, 0, 0)$ e apliquemos o teorema de Pitágoras:
    \begin{equation}
      \overline{OP^\prime}^2 = \overline{OA}^2 + \overline{AP^\prime}^2  = x^2 + y^2. \label{eq:1.3.1}
    \end{equation}
    %%
    EM seguida, consideremos o triânguloa $OP^\prime P$, reto em $P^\prime$ e apliquemos o teorema de Pitágoras:
    \begin{align}
      \overline{OP}^2 = \overline{OP^\prime}^2 + \overline{P^\prime P}^2 \Rightarrow \overline{OP}^2 = \overline{OP^\prime}^2 + z^2 \nonumber \\
      \Rightarrow r^2 = \overline{OP^\prime}^2 + z^2 \label{eq:1.3.2}
    \end{align}
    Substituindo $\overline{OP^\prime}^2$ de (\ref{eq:1.3.1}) em (\ref{eq:1.3.2}), obtemos:
    $$
    r^2 = x^2 +y^2 + z^2.
    $$
  \fimSol
\end{enumerate}